name: Mirror to GitLab
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (mirror completo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror para o GitLab
        run: |
          git remote add gitlab https://oauth2:${{ glpat-13OGq1o9dXrG9Hc4tPzFhGM6MQpvOjEKdTpoODUwdQ8.01.170sa6ctk }}@gitlab.com/projeto-desenvolvimento-2/2026-1-ygor-lucas.git
          git push gitlab --mirror